### ISSUE TITLE
Manage labels according to config file

### ISSUE THREAD

**Issue by ezhlobo** [frontrockets/pethov#1]
We can put our configuration into `.github/pethov.yml`.

For labels we can keep this schema:

```yml
labels:
  - name: WIP
    color: 3c5fb7
    description: Work In Progress

  - name: DX
    color: 018730
    description: Developer Experience

  - name: Postponed
    color: fff2a3
    description: We'll back later or keep for references
```
